### ISSUE TITLE
Add error handling to skip alt data files that don't exist

### ISSUE THREAD

**Issue by regnans** [TESTgroup-BNL/CSVQA#7]
2021-01-08 12:12:20,944 [INFO]: [Chamber 1 - Blue_Min1.dat]     Checking for duplicates in ['TIMESTAMP', 'RECORD']...
2021-01-08 12:12:21,016 [INFO]: [Chamber 1 - Blue_Min1.dat]     Found 8216 duplicates
2021-01-08 12:12:21,250 [INFO]: [Chamber 1 - Blue_Min1.dat]             Dropped duplicates, kept last.
2021-01-08 12:12:21,250 [INFO]: [Chamber 1 - Blue_Min1.dat]     Checking for duplicates in TIMESTAMP...
2021-01-08 12:12:21,281 [INFO]: [Chamber 1 - Blue_Min1.dat]     No duplicates found.
2021-01-08 12:12:21,281 [INFO]: [Chamber 1 - Blue_Min1.dat]     Checking record order...
2021-01-08 12:12:21,281 [INFO]: [Chamber 1 - Blue_Min1.dat]             No out of order timestamps found.
2021-01-08 12:12:21,281 [INFO]: [Chamber 1 - Blue_Min1.dat]     Checking for missings rows...
2021-01-08 12:12:21,547 [INFO]: [Chamber 1 - Blue_Min1.dat]             Filled 384815 missing rows
2021-01-08 12:12:52,828 [INFO]: [Chamber 1 - Blue_Min1.dat]     Loading ../Raw\Chamber 1 - Blue_Min1_alt.dat...
2021-01-08 12:12:52,828 [WARNING]:      [Chamber 1 - Blue_Min1_alt.dat] Problem while loading Chamber 1 - Blue_Min1_alt.dat: [Errno 2] No such file or directory: '../Raw\\Chamber 1 - Blue_Min1_alt.dat'
2021-01-08 12:12:52,828 [INFO]: [Chamber 1 - Blue_Min1_alt.dat] Checking for duplicates in TIMESTAMP...
2021-01-08 12:12:52,966 [INFO]: [Chamber 1 - Blue_Min1_alt.dat] No duplicates found.
2021-01-08 12:12:52,969 [INFO]: [Chamber 1 - Blue_Min1_alt.dat] Checking record order...
Traceback (most recent call last):
  File "T:\Projects\NGEE-Arctic\ZPW\2019\Data\QA\Level0to1.py", line 359, in <module>
    d_dev = calcAltDevs(d, fname, **opts["Level 1"], **opts["Input"])
  File "T:\Projects\NGEE-Arctic\ZPW\2019\Data\QA\Level0to1.py", line 211, in calcAltDevs
    checkOrder(d_alt)
  File "T:\Projects\NGEE-Arctic\ZPW\2019\Data\QA\Level0to1.py", line 184, in checkOrder
    if df[ts].is_monotonic:
TypeError: 'NoneType' object is not subscriptable[
[Level0to1_2021-01-08_121217.log](https://github.com/TESTgroup-BNL/CSVQA/files/5788554/Level0to1_2021-01-08_121217.log)
](url)

**Comment by amcmahon01** [comment]
There is a altCheckEnable flag in the config (line 61) that you can set to False if there isn't any alternate data, which will prevent this, though the error handling should be improved to skip trying to process a file that doesn't exist.  It does this already for different fields within a file but it appears that logic never made it to the top (file) level.  I'm renaming this issue to make it into a "to do".

**Comment by regnans** [comment]
Thanks! Glad that was an easy fix. Am running it again now. Looks like it is working, at least the alt data issue is fixed.
